### ISSUE TITLE
rename binary to ocamlmdx

### ISSUE THREAD

**Issue by avsm** [realworldocaml/mdx#100]
This will likely be an ocaml-specific tool for some time, so it'll ease packaging if we rename it to ocamlmdx sooner rather than later. Especially before it starts getting embedded in 3rd party projects...

**Comment by clecat** [comment]
Should it be `ocamlmdx` or `ocaml-mdx` ?

**Comment by avsm** [comment]
ocaml-mdx seems cleaner

**Comment by clecat** [comment]
I added a small warning when using mdx instead of ocaml-mdx: is the message good enough or do you have special expectations for his format ? @avsm

**Comment by clecat** [comment]
Better with the message ;)
```
Warning: 'mdx' is deprecated and will be removed in the futur
    Use 'ocaml-mdx' instead
```
