### ISSUE TITLE
Reintroduce craml syntax

### ISSUE THREAD

**Issue by trefis** [realworldocaml/mdx#104]
I'm using mdx only for tests, not for fancy documents, and for that purpose [craml](https://github.com/realworldocaml/craml#craml-a-tool-for-testing-command-line-applications)'s syntax was just more convenient.

I'm wondering if it could be reintroduce either with a `--syntax cram` flag, or by simply assuming that if the input is a `.t` file then it will be written in the cram syntax.

**Comment by avsm** [comment]
There's nothing imcompatible about having this just integrated by default in mdx as well, is there?  It seems like a useful thing to have alongside the existing codeblock markdown format.

**Comment by samoht** [comment]
Fixed by #106
