### ISSUE TITLE
Combining skip with other labels

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/mdx#135]
It would be really convenient to be able to add the `skip` label to an `ocaml` or `sh` snippet without having to remove other labels.

For example if I have the following snippet in my `.md` file:
```markdown
```sh dir=./some/dir
$ some-command
Some output
``
```

I'd like to be able to skip it without having to remove the `dir` label, which can be useful for temporarily disable it while debugging for instance. In other word I'd like to be able to write:
```markdown
```sh skip dir=./some/dir
$ some-command
Some output
``
```
and have it just skip that snippet's execution.

Currently what happens is that I get the following diff if I place `skip` before `dir`:
```diff
  ```sh skip dir=./some/dir
+ >> 
+ "skip dir" is not a valid label or prefix. Valid labels are "dir", "source-tree", "file", "part", "env", "skip", "non-deterministic" and "version" and valid prefixes are "set-".
  $ some-command
```

and the following error if I place it after:
```
$ ocaml-mdx test --prelude=prelude.ml --direction=to-ml README.md
ocaml-mdx-test: internal error, uncaught exception:
                (Sys_error
                  "./some/dir skip: No such file or directory")
```

Do you think that would  be possible and would make sense? If not I guess we could at least improve the error reporting a bit to make it clear only one those labels can be used at a time!

I'm of course happy to contribute a fix.

Let me know what you think!

**Comment by NathanReb** [comment]
@clecat pointed that it's just a syntax error and that labels must be separated by a comma, no space like the following:
```
```sh skip,dir=./some/dir
$ some-command
Some output
``
```

Specifying that syntax in some kind of `mdx` manual or to extend the current README would be very helpful as I couldn't find documentation for it although I admit I haven't looked for a very long time!

**Comment by gpetiot** [comment]
The doc was improved by #234
