### ISSUE TITLE
mdx sometimes add trailing whitespaces

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/mdx#146]
Mdx appear to sometime add trailing whitespaces to toplevel evaluations. See an example of this behaviour [here](https://github.com/realworldocaml/book/pull/3100/commits/17abdfa156d7d91fb7d80dea9091dc0ed61efecf#diff-0ddf0bd6914c9962843f0b23ed6009caR710).

I haven't had time to investigate why this happened but I'm guessing it could be fixed by systematically stripping trailing whitespaces from toplevel evaluations as there's no value in keeping them around even if the toplevel did return them.

**Comment by samoht** [comment]
@clecat can you have a look at this? I think we changed that code recently.

**Comment by clecat** [comment]
I'll give a look at it

**Comment by clecat** [comment]
We should close this issue now
