### ISSUE TITLE
When using mdx with to-ml direction, attributes are followed by ;;

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/mdx#147]
It appears that this was recently introduced. See an example [here](https://github.com/realworldocaml/book/pull/3100/commits/b9dd293f1406236198ddf42d8f846ee10aa35f63#diff-f3a1ed294d85c4e18aaceaa24fd7c865R16).

Is there any particular reason for that?

**Comment by gpetiot** [comment]
The synchronization in the `to-ml` direction has been removed in #214 so I'm closing this issue.
