### ISSUE TITLE
Not working properly with ocaml-4.08.1+rc3

### ISSUE THREAD

**Issue by RiderALT** [realworldocaml/mdx#151]
After upgrade to ocaml-4.08.1+rc3 make test fails:
(cd _build/default/test && ../../install/default/bin/ocaml-mdx test empty_line.md)
ocaml-mdx-test: internal error, uncaught exception:
                Failure("incomplete OCaml version")

# Sys.ocaml_version;;
- : string = "4.08.1+rc3"

**Comment by gpetiot** [comment]
Related to #144 
@samoht what do you think of using https://github.com/dividat/ocaml-semver instead of parsing the ocaml version number ourselves?

**Comment by samoht** [comment]
Using a dedicated (and well tested library) is a good idea. In that case we should be using https://github.com/avsm/ocaml-version which is already used in production by the CI infrastructure.
