### ISSUE TITLE
Mdx ignore new parts when syncing in to-ml direction

### ISSUE THREAD

**Issue by Julow** [realworldocaml/mdx#154]
I have a `README.md` defining a part to sync:

````md
Blabla:

```ocaml file=test.ml,part=1
let f x = x
```
````

and a `test.ml`:

```ocaml
[@@@part "1"]

let f x = x
```

If I add a new part in the README, eg.

````md

Part 2:

```ocaml file=test.ml,part=2
let g f x = f x
```
````

running mdx with `--direction=to-ml` won't update the `test.ml` file.

**Comment by NathanReb** [comment]
I believe this is related to #148 !
