### ISSUE TITLE
Explicit ocaml block types

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/mdx#164]
I'm a bit confused by all the possible type of ocaml blocks mdx interprets, toplevel, code, code extracted from a file and I'm not sure how it behaves in each cases.

From a user perspective it can be a bit puzzling. I think a first step is to add proper documentation. I'll try to take care of that first part in the next few days but I think it might be worth re-thinking the how these blocks are specified and eventually let the user be explicit about it.

That would probably break mdx's API so we need to think carefully about how to handle all this but I think in the end the `mdx`'s code base would benefit from it as we could get rid of all the "guessing" logic!

**Comment by gpetiot** [comment]
I made a survey of the existing labels:
- `dir`
- `source-tree`
- `file`
- `part` : only for OCaml and Toplevel blocks, requires `file`
- `env`
- `skip`
- `non-deterministic`
- `version` : should only be applied to OCaml and Toplevel blocks
- `require-package` : should only be applied to OCaml and Toplevel blocks
- `set-*`
- `unset-*`

It seems `part`, `version` and `require-package` should be restricted to OCaml and Toplevel blocks, and the others can be applied to any block.
We can redesign the definition of blocks to integrate the appropriate labels depending on their kind.

**Comment by NathanReb** [comment]
We should probably take this discussion to a separate PR as it's a bit of separate concern.
The original issue is about allowing to explicitly set the kind of block, ie something like `kind=ocaml-toplevel`, `kind=file-include` or `kind=shell` whereas what you're mentioning is early handling of misused labels. I'll open an issue and quote you from there!

**Comment by NathanReb** [comment]
Also I don't think the type of block as written after the triple backticks in markdown files should be considered as the source of truth since it's only there for syntax highlighting in the rendered markdown.

To clarify I'm not saying that mdx should never try to infer the type of a block if the users don't want to bother with labels sometimes but that there should at least be a way to explicitly define for the case where inference is hard or impossible.

**Comment by NathanReb** [comment]
For future reference I consider that atm the following type of code blocks are considered by mdx. Once again, those are unrelated to the syntax of the block but rather to the way mdx will treat them:
1. OCaml toplevel blocks. They are made of a sequence of toplevel phrases followed by their evaluations. Mdx will copy and run the phrases in a toplevel and print their evaluation in the corrected file.
2. Shell blocks. They contain a series of shell commands followed by their output. Mdx will copy and run the commands and print their output in the corrected file.
3. File include blocks. They contain arbitrary code or text. Mdx will extract the file content or part of it and prints them in the corrected file. No validation of any  kind is applied here, it just pulls in the file as it is and it is the user's responsibility to ensure the content of the file is valid.
4. Regular OCaml blocks. These blocks just contains regular ocaml code. Mdx will run them in a toplevel but won't print the evaluation. If evaluation fails, `ocaml-mdx test` will exit abnormaly and print the error on its stdout.

4. and 1. are very similar except that 4. doesn't use a special syntax (the leading `#`) and doesn't show the eval.
I think they could probably be merged into one and improved a bit. For example the errors in 4. shouldn't stop mdx, it should probably instead print the error in the corrected file so that it integrates better with the rest of the workflow. The endgame here is to have all of those features integrate nicely with merlin so you get the errors as you work on your markdown file but I still think we should go promotion workflow all the way.

**Comment by samoht** [comment]
> For example the errors in 4 shouldn't stop mdx, it should probably instead print the error in the corrected file so that it integrates better with the rest of the workflow.

That's a good idea, but it's not clear to me how this will work. Creating a comment in the code with the error could work but we need to remove it once it the error disappear. But just a final (and optional) section at the end of the block is enough. We already have this for 3 to show exit codes.
