### ISSUE TITLE
Improve part delimiters

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/mdx#165]
I think there are a few issues with how `mdx` delimits parts:
1. They are not clearly identified as being interpreted by `mdx` and that can be confusing. `[@@@mdx.part ...]` would be better
2. They aren't actual delimiters and its not very user friendly. Separate begin and end markers for a given part would be better than having to introduce `[@@@part 2]` to mark the end of the part 1 even though no part 2 is ever used anywhere.
3. The fact that they are attributes can be slightly confusing as those usually have meaning. One could think they are interpreted by a PPX and expanded into something. Is there any reason why this isn't done using comments instead?

**Comment by gpetiot** [comment]
It was done using attributes to reuse as many bits from https://github.com/realworldocaml/topexpect/tree/master/lib as possible, I agree it may be confusing from a user perspective.

**Comment by samoht** [comment]
Parts are not always defining valid sub-ast do I’m not even sure using attributes is a good idea. We are now even using regexps to identify them...

**Comment by NathanReb** [comment]
What would you think about adding clearer begin/end delimiters using comments?

In a first iteration we could support both those and the old parts attributes to avoid making a huge breaking change. We could then get rid of the attributes when bumping the major version!

**Comment by NathanReb** [comment]
Something like:
```
(* mdx-part-begin <part_name> *)
...
(* mdx-part-end *)
```

**Comment by yminsky** [comment]
No objections from me.

**Comment by NathanReb** [comment]
cc @voodoos

**Comment by Julow** [comment]
The concrete syntax can be shared with https://github.com/realworldocaml/mdx/issues/205 for consistency (useful if we ever need to have labels or expect users to type them manually).

Something like:
```
(* $MDX part-begin=<part_name> *)
...
(* $MDX part-end *)
```

I think the `$` can be dropped
