### ISSUE TITLE
Always generate .corrected files when used in dune

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/mdx#168]
While toying around with `mdx.1.4.0` I stumbled upon the bug fixed by https://github.com/realworldocaml/mdx/pull/136. This bug is now fixed but one thing I noticed is that it manifested in a really weird and disturbing way if you used `ocaml-mdx rule` to generate your mdx test rules.

Because the generated rule uses `(diff? %{x} %{x}.corrected)` actions, it will silently pass if no `.corrected` file has been generated.

I'm wondering if it wouldn't be more robust to have `ocaml-mdx rule` to produce a rule that generates all the `.corrected` no matter what, using the `--force-output` option of `ocaml-mdx test` and to produce strict diff rules thus preventing any such silent failures.

Let me know what you think!

**Comment by samoht** [comment]
See https://github.com/ocaml/dune/issues/2482

**Comment by NathanReb** [comment]
I'm not sure it's related as the issue here was that nothing happened because the second argument of `diff?` was missing (ie wasn't generated by MDX). I might be misunderstanding this but I don't think the new `diff?` will change that.

**Comment by NathanReb** [comment]
In other words `diff?` behaved as it was supposed to but that made it hard to even know there was a bug in the first place.

**Comment by samoht** [comment]
Isn't this a similar issue that @clecat had in https://github.com/ocaml/dune/issues/2396 ?

But if the real issue is that `mdx` doesn't generate a `.corrected` file when it should, it will be better to just fix that issue instead of trying to work-around possible bugs.

**Comment by NathanReb** [comment]
I'm closing this as:
1. it is not entirely true, Jenga still relies on this behaviour (i.e. running the diff ourself in mdx)
2. we now have a dune stanza which forces that behaviour by passing `--force-output` anyway
