### ISSUE TITLE
Report #require directive errors

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/mdx#200]
Until we have a better way to handle toplevel fragments we need to report errors from `#require` directive.

Currently what happens is that the directive can fail silently and the error mode is a quite unhelpful `Unbound module X` message.

The way `Topfind` report errors isn't great as it simply prints them to stdout but it seems that we're somehow capturing those.

Hopefully that won't be a problem in the future as we won't rely on those directives to use packages in the toplevel but until then it would prove very helpful to debug issues in RWO which relies on master!

**Comment by gpetiot** [comment]
Do you have examples of failures? I made an experiment to fix it locally but I can't reproduce the issue (besides messing up my ocaml setup)
