### ISSUE TITLE
Alternative label declaration in markdown comments

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/mdx#205]
Currenlty mdx labels follow the opening of the block like this:
```
```ocaml env=main,...
```

The issue is that not all markdown processing tools will ignore those, for instance pandoc doesn't. I also know @CraigFe has encountered issues of its own with mdx labels.

The idea would be to provide an alternative using markdown comments as defined in [CommonMark](https://spec.commonmark.org/0.29/). It would look something like:
```
<!-- $MDX env=main ... -->
```ocaml
```

That would ultimately completely replace the current form in the long run so that markdown files meant to be consumed by mdx can also be fed to any standard markdown processing tool.

**Comment by NathanReb** [comment]
I'll try to do a survey and see how many tools support this syntax for comments before moving further on this!

**Comment by NathanReb** [comment]
Cc @voodoos

**Comment by samoht** [comment]
That seems like a really good idea!

**Comment by voodoos** [comment]
Survey:

I guess the three following behaviours can be expected:

Name | Behavior | Good for us?
------------ | --------- | ------------
`hard` | The comment is not present at all after processing the markdown | Good
`soft` | The comment is rendered as html code and won't show in a browser but still be present in the source file | Good enough ™️ 
`shown` | The comment is rendered as visible text | Bad

Renderer | Behaviour
------------ | -------------
Github | `hard`
Pandoc: md -> html | `soft`
Pandoc: md -> latex | `hard`
OCaml OMD | `soft`
Random vscode plugin | `soft`
https://dillinger.io/ | **`shown`**
https://stackedit.io/ | `soft`
Other tool | probably `soft`

Luckily it looks like the last behavior (that would be very bad) is not widely used. I shown only in one of the random in-browser markdown editors I tried.

After checking `dillinger.io` is using `markdown-it` which by default does not enable html tags in markdown. And stackedit also use `markdown-it`.

**Comment by NathanReb** [comment]
How do those behave with our current label syntax ? If Dillinger and stackedit don't support those either I would hardly consider the new syntax a regression. Could you give the current syntax a try and update the table ?

**Comment by voodoos** [comment]
Done.

It is clearly an overall improvement.

**Comment by CraigFe** [comment]
FWIW, I think the `soft` behaviour is the 'correct' one by the specification. The CommonMark spec defines these as supported HTML elements, so it makes sense for these to be included in any HTML rendering of the markdown content. I don't see this as an issue per-se.

I think Dillinger is just broken / intentionally incomplete in this case (depending on your point of view). Certainly their decision to escape HTML in the way they do is contentious: https://github.com/joemccann/dillinger/issues/325.

**Comment by voodoos** [comment]
So the take-away is: yes we should definitively move to these new labels.

I guess we should wait for the merging of #221 ?
