### ISSUE TITLE
Report inconsistent blocks at parsing time

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/mdx#216]
Not all labels or combination of labels are allowed for every block in mdx. This not consistenlty handled at the moment. In some cases, `ocaml-mdx test` will fail and report these errors, in some others the labels will simply be ignored silently.

It would be nice to always report those errors at parsing time to both make it clearer to users what is allowed and what is not and to centralize those concerns in a single place in the code. Piece of code consuming blocks wouldn't have to ensure they are valid then.

**Comment by gpetiot** [comment]
Here is a survey of the existing labels:
- `dir`
- `source-tree`
- `file`
- `part` : only for OCaml and Toplevel blocks, requires `file`
- `env`
- `skip`
- `non-deterministic`
- `version` : should only be applied to OCaml and Toplevel blocks
- `require-package` : should only be applied to OCaml and Toplevel blocks
- `set-*`
- `unset-*`

It seems `part`, `version` and `require-package` should be restricted to OCaml and Toplevel blocks, and the others can be applied to any block.
We can redesign the definition of blocks to integrate the appropriate labels depending on their kind.

**Comment by NathanReb** [comment]
I posted this message in #164 but it's also going to help here:

> For future reference I consider that atm the following type of code blocks are considered by mdx. Once again, those are unrelated to the syntax of the block but rather to the way mdx will treat them:
> 
> 1. OCaml toplevel blocks. They are made of a sequence of toplevel phrases followed by their evaluations. Mdx will copy and run the phrases in a toplevel and print their evaluation in the corrected file.
> 2. Shell blocks. They contain a series of shell commands followed by their output. Mdx will copy and run the commands and print their output in the corrected file.
> 3. File include blocks. They contain arbitrary code or text. Mdx will extract the file content or part of it and prints them in the corrected file. No validation of any kind is applied here, it just pulls in the file as it is and it is the user's responsibility to ensure the content of the file is valid.
> 4. Regular OCaml blocks. These blocks just contains regular ocaml code. Mdx will run them in a toplevel but won't print the evaluation. If evaluation fails, ocaml-mdx test will exit abnormaly and print the error on its stdout.
> 
> 4 and 1 are very similar except that 4 doesn't use a special syntax (the leading #) and doesn't show the eval.
I think they could probably be merged into one and improved a bit. For example the errors in 4 shouldn't stop mdx, it should probably instead print the error in the corrected file so that it integrates better with the rest of the workflow. The endgame here is to have all of those features integrate nicely with merlin so you get the errors as you work on your markdown file but I still think we should go promotion workflow all the way.

**Comment by gpetiot** [comment]
Yes, I think #164 would be a prerequisite of fixing this issue, once we have more specialized blocks with specific types it would be sense to  add fields to these types for the allowed labels of each kind of blocks.

**Comment by NathanReb** [comment]
I'll use the numbers from the previous message for the type of blocks.

Here's what I know for sure:
- `skip` is valid for every single block
- `non-deterministic` is valid for every single block
- `version` is valid for every single block, for example imagne that you have a shell block that relies
  on an executable that's not available on all ocaml versions.
- `env` is only valid for 1 and 4
- `file` is only valid for 3 (and mandatory in this case)
- `part` is only valid for 3 and as of today, only if `file` points to `.ml` or `.mli` file but that's a bit trickier to check so we could leave it out in a first iteration.

As far as I know `source-tree` and `require-package` are only used by mdx-rule and we will get rid of them with the dune integration as users will specify those dependencies in the mdx stanza rather than in the file. In the meantime they should be accepted on all blocks since they are indeed interpreted no matter what the block is.

`set-` and `unset-` I don't know anything about yet but I'll take a look!

**Comment by NathanReb** [comment]
I don't think #164 is a pre-requisite at all. We already have block type dispatch logic in the code, we can move that logic earlier, right after a block is parsed.

This issue is about the feature, ie proper error reporting of labels misuse so in a first iteration, we can just have some kind of `check : Block.t -> errors list` function and make sure that when we parse a document, we collect all such errors, and if the list is non empty we report them and fail. Probably worth collecting errors for all blocks before failing.
I think the focus here is to have the improved error reporting and the associated end-to-end tests.

In a second phase we can improve the block parsing and make the type for blocks so that only consistent values can be built, ie have some kind of `from_raw: Block.raw -> (Block.t, error list) result` function and only have the rest of the code handle `Block.t`. In that example, `Block.raw` would be our current `Block.t`.

What do you think?

**Comment by NathanReb** [comment]
It would also be nice to properly document all labels and where they can be used but for this we probably also need to polish the documentation about the different kind of blocks.

**Comment by gpetiot** [comment]
I thought the `file` label was valid for any block, as we would include either toplevel phrases, OCaml code or shell commands. There is currently some code processing this label for OCaml, Toplevel, Cram and Raw type of blocks for the synchronization.
