### ISSUE TITLE
Print errors in raw ocaml blocks rather than failing

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/mdx#219]
When the evaluation of a raw OCaml block fails in mdx, the execution stops immediately and the error is reported on stderr.

This does not integrate nicely with the rest of the `mdx test` workflow. I think there's more value in reporting other errors as well. I also believe that since the error will be displayed next to the code and the text it will make more sense to the user and that without any further effort on our side to properly display it.

In addition it would bring raw ocaml blocks behaviour a bit closer to ocaml toplevel blocks which I believe makes sense since they already have very few differences and are meant to be mixed and work together well.

Finally, this could eventually be seen as a feature if one wishes to purposefully write erroneous code to showcase the associated compiler error.

**Comment by NathanReb** [comment]
CC @samoht @yminsky @avsm.

I'm curious to hear your thoughts on this!

**Comment by Julow** [comment]
On the other hand, stopping at the first error avoid cascading errors when a block depends on previous blocks.

**Comment by NathanReb** [comment]
I agree but since it already happens with toplevel blocks I think consistency would justify that.

The main advantage is that not all subsequent errors are necessarily related to this, ie other toplevel env, erros in file-include or shell blocks etc...

**Comment by samoht** [comment]
That sounds like a good idea, see https://github.com/realworldocaml/mdx/issues/164#issuecomment-580725151 for a proposal.

Also note that toplevels can support errors, but this is due to the toplevel mixing up errors and expression outputs. Maybe we can also improve the toplevel and separate the two streams (as I believe utop does it), and have a unified concrete syntax to report errors in mdx.

**Comment by NathanReb** [comment]
I think that the fact that toplevel blocks have error displayed is in fact a feature, it's used in RWO for instance. I'm note sure we should separate the two streams. I believe the closer it looks to running an actual toplevel, the better.

My impression is that raw ocaml blocks should basically just be treated as toplevel blocks for which we just don't how the successful evaluations.

If I understand it correctly, a raw ocaml block is evaluated as a single toplevel phrase, which means that if we were to display the error the same way we do it for toplevel block, there would just be a single error at the end of the block anyway. I think that would be a good behaviour

The comment thing seems a bit convoluted and adds quite a lot of logic on the mdx side. I think I'd prefer prefexing the error code with a marker, something like `> ` or whatever would best fit that purpose.

To sum up, what I'm suggesting is that, for the following markdown:
```md
The following code does something:

```ocaml
let succ x = x + 1

let f x = 1 / succ x

let i = f 0.
``
```
MDX would generated the following correction:
```md
The following code does something:

```ocaml
let succ x = x + 1

let f x = 1 / succ x

let i = f 0.
> Error: This expression has type float but an expression was expected of type
>          int
``
```

That seems both easy to implement in the current state of things and fairly clear from a user perspective.

What would you think of such a solution?

In the future we could think about allowing a similar syntax for toplevel blocks as well although it would probably require us to unify raw and toplevel blocks a bit more. For instance we could make them a single block type, allow silencing evals locally via a label and always allow both syntax, ie highlight phrases with `# ` or highlight evals/erros with `> `.

**Comment by samoht** [comment]
Regarding the tolpelevel mixing outputs: I think that's a flow (and it's an issue in various use-cases, like `js_of_ocaml` toplevels where we have to use ugly hacks to distinguish the two for instance) , but that needs to be fixed upstream anyway.

Regarding your syntax: why not, but you will have to handle special corner cases like:
```ocaml
let x = {|
> Error: .... |}
```
Maybe just generate the error in an attribute?

**Comment by NathanReb** [comment]
Very good point about that corner case. It's annoying but I guess it will be true of any syntax we choose for the errors unfortunately.

In particular I'm struggling to see how an attribute would help.

Ie, if we consider the following:
```md
```ocaml
let x = 1 + 0.
``
```
would mdx generate the following correction:
```md
```ocaml
let x = 1 + 0.
[@@error "<insert compile error msg>"]
``
```
?

But then how would you distinguish that attribute used by mdx to indicate a compile error from that exact same attribute, intentionally attached?

Even more concerning, how would the reader of the rendered markdown know what that attribute is, especially if he's not an mdx user?

I think the main advantage of my proposal is that it's not valid ocaml syntax and therefore it cannot be mistaken for something it's not which comment and attributes could.

Even though it doesn't prevent us from handling multiline strings, at least it is always possible to distinguish it from actual code.

**Comment by NathanReb** [comment]
An alternative could be to print it in a subsequent block, right after the original one, marked as:
```md
```mdx-error
```
