### ISSUE TITLE
Loading preludes for various environments

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/mdx#226]
There seem to be a few bugs with preludes. Preludes can be loaded for the default env by passing
`--prelude <ml-file>` or for a specific one by passing `--prelude <env-name>:<ml-file>`.

I would expect this to behave just as regular toplevel blocks would, ie the default environment is just a separate environment.

I ran into a weird bug where the default env seems to be contaminated by preludes loaded for other envs.
Another disturbing behaviour is that if I load the default env prelude last, it doesn't seem to be loaded at all.

I reproduced this behaviour in a draft PR [here](https://github.com/realworldocaml/mdx/pull/225/files#diff-6462388d32e1f535eafb3d27e9212b2a).

I belive this should be fixable as it seems that it all works well if only using named envs but I think it raises questions about the prelude, the envs and how they should behave. Should the default env preludes be loaded for every env? Just the default one?

I also think we should probably not allow more than one prelude per env (default one included) as otherwise we have to take the order of CLI arguments into account and that seems a bit odd.

**Comment by NathanReb** [comment]
The current behaviour seems to be that a default prelude is loaded for every env. That seems like a feature as I guess one might want to use that to register printers or define global variables for all envs so we should preserve that.

**Comment by gpetiot** [comment]
The bugs are fixed by #225
