### ISSUE TITLE
Use csexp package from opam 

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/mdx#236]
We should use the new https://github.com/diml/csexp instead of having our own local copy to output csexp in `mdx dep`.

**Comment by gpetiot** [comment]
https://github.com/ocaml/opam-repository/pull/15990

**Comment by NathanReb** [comment]
Argh it requires ocaml >= 4.03, we'll have to wait until we can drop support for 4.02 to use it :/

**Comment by gpetiot** [comment]
The required version is now 4.04
