### ISSUE TITLE
Environment variable setting breaks on variables with underscore

### ISSUE THREAD

**Issue by shonfeder** [realworldocaml/mdx#254]
This should be a minimal reproducing example:

    ```sh set-SOME_VAR=foo
    $ echo 
    ```

Fails with

```
invalid code block: Label `set-SOME_VAR=foo` requires a value.
```

**Comment by NathanReb** [comment]
Thanks for reporting this!

This should be fairly easy to fix. I think the [regexp in label.ml](https://github.com/realworldocaml/mdx/blob/master/lib/label.ml#L54) doesn't capture underscores for some reason.

If you'd like to try fixing it I'm happy to point you in the right direction!

**Comment by shonfeder** [comment]
Thanks @NathanReb. I opened #257 at your suggestion. Any pointers for additional changes/tests I should add would be most welcome.
