### ISSUE TITLE
The README is out of date

### ISSUE THREAD

**Issue by shonfeder** [realworldocaml/mdx#255]
It looks like, at least, the tag syntax and the dune stanza's in the README are out of date. 

It would probably be helpful to put the tutorial material under test, by preprocessing the dune stanzas into the markdown and running the README through mdx itself itself (or something).

(btw, I've had a fantastic time making use of this library! :) )

**Comment by gpetiot** [comment]
Hi, the tag syntax presented in the README (the HTML comments) is the "new" syntax, it's the only one advised in the README. The "old" syntax (in the block header) is still supported for now for legacy users, but may disappear in future versions (and is still used in the tests).

(I haven't followed the recent developments for the dune stanza, it may be out of date indeed)

**Comment by shonfeder** [comment]
Oh interesting. Something must be amiss with my installation then. Perhaps the new tag syntax isn't released? Here's a minimal example:

With 

```sh
$ ocaml-mdx --version
1.6.0
```

In `min-example.md`, I have

    ```sh set-FOO=foo
    $ echo $FOO
    ```

    
    ```sh
    $ echo $BAR
    ```

And the first first sets the env var as expected but the second doesn't:

```sh
$ ocaml-mdx test ./min-example.md && diff min-example.md min-example.md.corrected 
2a3
> foo
7a9
> 
```

**Comment by shonfeder** [comment]
Ah yeah, that's it. I pinned to this repo (instead of installing from opam), and it's now working as documented:

```sh
$ ocaml-mdx test ./min-example.md && diff min-example.md min-example.md.corrected 
2a3
> foo
7a9
> bar
```

**Comment by NathanReb** [comment]
Yeah it's not released yet.

We should be able to cut a release soon though as quite a lot of features and fixes have been merged since the last one. We'll also work on the documentation as I think not all features are documented atm. In particular we should also mention the dune stanza in the README!
