### ISSUE TITLE
Properly report errors in mdx deps

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/mdx#264]
`ocaml-mdx deps` seems to let some errors slip through as uncaught exceptions.

I think that for clarity it would be better if used `result` or at least our own exceptions so that we can catch mdx related errors and report them ourself rather than leak those uncaught exceptions.

As an example, when labels are invalide, one gets the following:
```
ocaml-mdx book/foreign-function-interface/README.md.mdx.deps (exit 125)
(cd _build/default/book/foreign-function-interface && ../../../install/default/bin/ocaml-mdx deps README.md) > _build/default/book/foreign-function-interface/README.md.mdx.deps
ocaml-mdx: internal error, uncaught exception:
           Failure("File \"README.md\", line 230, character 371: invalid code block: `non-deterministic` label cannot be used with a `file` label.")
```

**Comment by gpetiot** [comment]
Closed with #267
