### ISSUE TITLE
Unable to turn on warning 6 in mdx block

### ISSUE THREAD

**Issue by jsomers** [realworldocaml/mdx#287]
In regular ocaml, this gives an error:

```ocaml
let () =
  let f ~x:() = () in
  f ()
;;
```

Here's the error message:

```
Error (warning 6): label x was omitted in the application of this function.
```

The same code appears to compile in an mdx ocaml block:

````md
```ocaml
let () =
  let f ~x:() = () in
  f ()
```
````

The usual annotation doesn't help. This still builds:

````md
```ocaml
[@@@warning "+6"]
let () =
  let f ~x:() = () in
  f ()
```
````

**Comment by gpetiot** [comment]
On a separate note the warning properly shows if the block is a toplevel evaluation:

    ```ocaml
    # [@@@warning "+6"]
    # let () =
      let f ~x:() = () in
      f ()
    Line 3, characters 3-4:
    Warning 6: label x was omitted in the application of this function.
    ```

**Comment by gpetiot** [comment]
after investigating more, it looks more difficult to display the output of the evaluation for ocaml blocks as we don't really have a clean way to distinguish warnings from the printing of the type/value resulting from the evaluation. As opposed to toplevel blocks as we would print everything that is returned upon evalution.

**Comment by yminsky** [comment]
I think the ideal behavior for ordinary "ocaml blocks" that don't generate any throwback would be for the build to straight-up fail if there are any errors, much as an ordinary OCaml compilation would fail.  i.e., don't have it show up as any kind of expect-style throwback, but just as an ordinary build error.  I think that lines up with that code not being run in a toplevel context.
