### ISSUE TITLE
$MDX delimiters in ocaml cut off any code on the same line

### ISSUE THREAD

**Issue by ceastlund** [realworldocaml/mdx#374]
If I write code like this:

```
(* $MDX part-begin=something *)
type t =
  | Foo
  | Bar (* $MDX part-end *)
```

Then what shows up in the MDX is:

```
type t =
  | Foo
```

This cuts off `| Bar`. Granted, a solution is to always put the comment on a separate line. But ocamlformat doesn't know this, for example. It would be better if mdx always preserved all the code between delimiters.

**Comment by NathanReb** [comment]
Out of curiosity, does ocamlformat still format it this way if you had an empty line between `| Bar` and the comment?

I understand this is annoying but I'm wondering if from a user perspective, you really want inline part delimiters. If there's no way to get ocamlformat and MDX to agree on how this, we'll of course fix it in MDX but I'm wondering whether this is the formatting you actually want or if you'd also rather have it on a separate line.

**Comment by Leonidas-from-XIV** [comment]
@ceastlund Thanks for the report and the example. I'm currently trying to implement a reasonable solution to this problem. Could you specify a configuration where OCamlformat formats the comment on the end of the line? I'm playing around with source code like this:

```ocaml
(* $MDX part-begin=something *)
type t =
  | Foo
  | Bar
  | Baz
  | Quuz
  | Fnuug
  | Gbaz of { foo : int; bar : int; baz : int; bat : int }
  | Hoog
(* $MDX part-end *)
```

to get ocamlformat 0.21 to put the `part-end` on the same line as `Hoog` but with both the `conventional` and `janestreet` profiles it leaves it on its own line (the `conventional` profile puts types with less variants on one line but the `part-end` stays on a separate line. Unfortunately, there's a ton of flags so it would be good to have a reproducible case that we can reach out to the OCamlformat maintainers to find a solution that is both readable and doesn't drop lines silently.

**Comment by ceastlund** [comment]
I believe the case I've run into is when there's an `[@@deriving]` clause on a new line after the comment, and the comment is aligned with the "|" on the previous line, it gets moved up to after "Hoog". And if it's after "Hoog", it stays there.
