### ISSUE TITLE
short-path in mdx?

### ISSUE THREAD

**Issue by c-cube** [realworldocaml/mdx#392]
hi, I'm wondering if there's a way to control the aliases and the type printing in mdx. I think `-short-paths` could be a good option but I'm not sure I can pass _any_ argument to the underlying toplevel?

**Comment by samoht** [comment]
mdx is using `-short-paths` since https://github.com/realworldocaml/mdx/commit/6fbe94a62694c41e7dec0c8cba06cd6a8ecae849 :-)

**Comment by c-cube** [comment]
I see. Then I wonder what I can do to improve the choice of paths… :/
