### ISSUE TITLE
Bug when using `Format` library.

### ISSUE THREAD

**Issue by panglesd** [realworldocaml/mdx#400]
The `Format` library, used in toplevel blocks, differs from what happens in the real toplevel.

If I have the following markdown file, in `/tmp/mdxtest.md`:
``````
```ocaml
#  let _ = Printf.printf "blabla" ;;
```
``````
then everything is as expected:
``````
$ ocaml-mdx test /tmp/mdxtest.md
$ cat /tmp/mdxtest.md.corrected 
```ocaml
# let _ = Printf.printf "blabla" ;;
blabla
- : unit = ()
```
``````

However, when using the `Format` module, the outputted string seems to escape `mdx`:
``````
$ cat /tmp/mdxtest.md
```ocaml
# let _ = Format.printf "blabla" ;;
```
$ ocaml-mdx test /tmp/mdxtest.md
blabla%                                                                                                                                                                            
$ cat /tmp/mdxtest.md.corrected 
```ocaml
# let _ = Format.printf "blabla" ;;
- : unit = ()
``````

This is in contrast with what happens in the ocaml toplevel, where the string is outputted directly. Moreover, when used in Dune, the behaviour becomes very confusing, with some outputted string being added (again and again) outside mdx blocks.

(Closing all boxes with `@.` or flushing with `%!` make the string be outputted. However, `flush_all()` do not seem to change anything.)

**Comment by Julow** [comment]
`flush_all` don't flush any of Format's buffer and Mdx is probably already doing it. Format's "standard" buffers can be flushed like this:
```ocaml
Format.pp_print_flush Format.std_formatter ();
Format.pp_print_flush Format.err_formatter ()
```

I don't think it's possible to close other buffers created by the user. (for example with `formatter_of_out_channel`)

**Comment by Julow** [comment]
`flush_all` don't flush any of Format's buffer and Mdx is probably already doing it. Format's "standard" buffers can be flushed like this:
```ocaml
Format.pp_print_flush Format.std_formatter ();
Format.pp_print_flush Format.err_formatter ()
```

I don't think it's possible to close other buffers created by the user. (for example with `formatter_of_out_channel`)

**Comment by panglesd** [comment]
Thanks for your answer. Yes, it makes sense that Mdx cannot close or flush buffers created by the user.

I wonder however if that would be possible to avoid printing its unflushed output to stdout:
```
$ ocaml-mdx test /tmp/mdxtest.md
blabla%
```
which makes Dune add `blabla` at the end of the `.corrected` file (but that could be seen as a wrong behaviour of dune).

In any case, it is the user responsibility to close its buffer, which solves the issue.

**Comment by Leonidas-from-XIV** [comment]
I am not sure, it doesn't look like Mdx ever flushes stdout/stderr formatters. It can't flush user-created formatters, but that's fine. Though I feel the formatters that are used in the toplevel should probably get flushed (and also not just randomly leak out the `ocaml-mdx` process which feels like a separate bug of not redirecting them to the right place)

**Comment by Julow** [comment]
Sorry, I meant to say that Mdx should flush the standard formatters.
