### ISSUE TITLE
concurrent environment modifies module paths

### ISSUE THREAD

**Issue by samoht** [realworldocaml/mdx#79]
For instance, if one environment loads `core`:

    ```ocaml env=core
     # #require "core";;
     # open Core
    ``` 

Other environment are (indirectly) impacted:

    ```ocaml env=non-core
    # let x = ref 1
    val x : int Stdlib.ref = {Stdlib.contents = 1}
    ```

Instead we would like the last signature to be:  `val x : int ref = {contents = 1}`

**Comment by gpetiot** [comment]
I guess this has been fixed along the way. On master, if I do : `mdx test test_core.md && diff test_core.md test_core.md.corrected` I get:
```
< val x : int Stdlib.ref = {Stdlib.contents = 1}
---
> val x : int ref = {contents = 1}
```
