### ISSUE TITLE
Support ocaml version constraints in code blocks

### ISSUE THREAD

**Issue by samoht** [realworldocaml/mdx#88]
Currently it is possible to specify that a code block should run for a given version of the OCaml compiler only (with `version=4.02` for instance). It would be nice to extend this feature with version constraints.

**Comment by gpetiot** [comment]
Would something with the following syntax work for you:
```
version=(<cmp> 4.02.3)
```
Where `<cmp>` could be eq, neq, lt, le, gt, ge for example?

**Comment by samoht** [comment]
Ideally it would be something like `version<4.02.0`. But your solution might be ok too if that's too complex to add.

**Comment by avsm** [comment]
The problem with `version>foo` is that it doesn't follow the `k=v` format of all the other qualifiers.  How about keeping it simple and having `min_ocaml_version` as a field? The vast number of cases will be covered either by `min_` or `max_` ocaml versions.

**Comment by samoht** [comment]
ok for `min-ocaml-version` and `max-ocaml-version` fields

**Comment by gpetiot** [comment]
This could be closed.

**Comment by avsm** [comment]
Would it be possible to document the feature in the README before closing it? I can't find any note in the docs on how to use the constraint field.

**Comment by gpetiot** [comment]
I updated the README in PR #101
