### ISSUE TITLE
comments before ocaml statements are rejected

### ISSUE THREAD

**Issue by c-cube** [realworldocaml/mdx#99]
somewhat similar to #35 but with comments:

    ```ocaml
    (* foo *)
    # 1+1;;
    ```

returns a syntax error.

**Comment by gpetiot** [comment]
Unfortunately this is the toplevel syntax, something like

    ```ocaml
    # (* foo *) ;;
    # 1+1;;
    ```

works, as well as:


    ```ocaml
    # (* foo *)
       1+1;;
    ```

**Comment by clecat** [comment]
I'm not sure allowing this is really relevant: I worked on it this morning, but the more I code, the more it feels odd.
As @gpetiot said, a commentary like this do not follow the toplevel syntax, so allowing it implies adding exceptions to the rules. It actually brings several changes in different parts of the code, which are not common to the actual behaviour.
Are we sure we want this ?

**Comment by samoht** [comment]
I'm closing this as I tend to agree with @gpetiot and @clecat ; all the solutions I have in mind for this are very ugly and would complicate the code-base for something which can be achieve by putting the comments inside a top-level expression :-)
